---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
    - ["private_network", {ip: "10.2.3.128"}]

provisioner:
  name: chef_solo
  attributes:
      citadel:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      balanced-apt:
        allow_unstable: true

platforms:
  - name: ubuntu-12.04
    driver_config:
      require_chef_omnibus: '11.10.4'
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
    - recipe[balanced-statsd-relayer]
